# serverless.yml

#组件信息
component: scf # (必选) 组件名称，在该实例中为scf
name: -Sunert-Scripts # (必选) 组件实例名称。

#组件参数配置
inputs:
  name: scf-${name} # 云函数名称，默认为 ${name}-${stage}-${app}
  enableRoleAuth: true # 默认会尝试创建 SCF_QcsRole 角色，如果不需要配置成 false 即可
  src: ./
  handler: index.main_handler #入口
  runtime: Nodejs12.16 # 运行环境 默认 Nodejs10.15
  region: ap-hongkong # 函数所在区域
  description: This is a function in ${app} application.
  memorySize: 128 # 内存大小，单位MB
  timeout: 900 # 超时时间，单位秒
  events: # 触发器
    - timer: # 中青看点
        parameters:
          name: youth
          cronExpression: "0 */5 * * * * *"
          enable: true
          argument: txnews
    - timer: # 腾讯新闻
        parameters:
          name: txnews
          cronExpression: "0 */5 * * * * *"
          enable: true
          argument: txnews
    - timer: # 电视家
        parameters:
          name: dianshijia
          cronExpression: "0 9 * * *"
          enable: true
          argument: dianshijia
    - timer: # 中青自动阅读
        parameters:
          name: youth_gain
          cronExpression: "0 3 */1 * * * *"
          enable: true
          argument: youth_gain
  environment: #  环境变量
    variables: #  环境变量对象
      AAA: BBB # 不要删除，用来格式化对齐追加的变量的
